import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import router from "./routes/index.js";
const app = new Hono();
app.use("*", cors({ origin: "*", allowMethods: ["GET", "OPTIONS"] }));
app.use("*", logger());
app.route("/api/v1", router);
app.get("/", (c) => c.json({ name: "HiAnime API", status: "running", endpoints: { home: "GET /api/v1/home", search: "GET /api/v1/search?keyword=naruto", anime: "GET /api/v1/anime/:id", episodes: "GET /api/v1/episodes/:id", servers: "GET /api/v1/servers?id=:episodeId", stream: "GET /api/v1/stream?id=:serverId" } }));
app.notFound((c) => c.json({ success: false, message: "Not found" }, 404));
app.onError((err, c) => c.json({ success: false, message: err.message }, 500));
const PORT = parseInt(process.env.PORT || "3030");
console.log(`HiAnime API running at http://localhost:${PORT}`);
export default { port: PORT, fetch: app.fetch, idleTimeout: 60 };